alcanza/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("blog/", include("blog.urls")),
    path("", include("web.urls")),
    path('rosetta/', include('rosetta.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
# blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name='post_list'),
    path('tag/<slug:tag_slug>/', views.PostListView.as_view(), name='post_list_by_tag'),
    path('<slug:slug>/', views.PostDetailView.as_view(), name='post_detail'),
]

web/urls.py
from django.urls import path
from django.conf.urls import include

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("residencia-canina", views.residencia_canina,
         name="residencia_canina"),
    path("educacion-canina", views.educacion_canina, name="educacion_canina"),
    path("intervenciones-asistidas-por-perros",
         views.intervenciones_asistidas_por_perros,
         name="intervenciones_asistidas_por_perros"),
    path("nuestro-club", views.nuestro_club, name="nuestro_club"),
    path("equipo", views.equipo, name="equipo"),
    path("contacto", views.contacto, name="contacto"),
    path("instalaciones", views.instalaciones, name="instalaciones"),

    # Cambio idoma
    path('language/', views.change_language, name='change_language'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from django.utils.text import slugify
from taggit.managers import TaggableManager
from django.utils.safestring import mark_safe
import markdown

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

    title = models.CharField(max_length=200, verbose_name="Título")
    slug = models.SlugField(
        max_length=200,
        unique=True,
        verbose_name="URL amigable"
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='blog_posts',
        verbose_name="Autor"
    )
    summary = models.TextField(
        max_length=500,
        verbose_name="Resumen",
        help_text="Breve resumen del post (máximo 500 caracteres)"
    )
    content = models.TextField(verbose_name="Contenido")
    featured_image = models.FileField(
        upload_to='blog/',
        blank=True,
        null=True,
        verbose_name="Imagen destacada"
    )
    tags = TaggableManager(verbose_name="Etiquetas", blank=True)
    
    # SEO Fields
    meta_description = models.CharField(
        max_length=160,
        blank=True,
        verbose_name="Meta descripción",
        help_text="Descripción para motores de búsqueda (máximo 160 caracteres)"
    )
    meta_keywords = models.CharField(
        max_length=255,
        blank=True,
        verbose_name="Meta palabras clave",
        help_text="Palabras clave separadas por comas"
    )
    
    publish = models.DateTimeField(default=timezone.now, verbose_name="Fecha de publicación")
    created = models.DateTimeField(auto_now_add=True, verbose_name="Fecha de creación")
    updated = models.DateTimeField(auto_now=True, verbose_name="Fecha de actualización")
    status = models.CharField(
        max_length=10,
        choices=STATUS_CHOICES,
        default='draft',
        verbose_name="Estado"
    )

    class Meta:
        ordering = ('-publish',)
        verbose_name = "Post"
        verbose_name_plural = "Posts"

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.slug])
    
    def get_markdown_content(self):
        # Convertir Markdown a HTML con extensiones comunes
        return mark_safe(markdown.markdown(
            self.content,
            extensions=[
                'markdown.extensions.fenced_code',
                'markdown.extensions.tables',
                'markdown.extensions.codehilite',
                'markdown.extensions.toc',
                'markdown.extensions.nl2br'
            ]
        ))

web/models.py
from django.db import models

# Create your models here.

blog/views.py
# blog/views.py
from django.views.generic import ListView, DetailView
from django.shortcuts import get_object_or_404
from .models import Post
from taggit.models import Tag
from django.db.models import Count

class PostListView(ListView):
    model = Post
    template_name = 'blog/list.html'
    context_object_name = 'posts'
    paginate_by = 6

    def get_queryset(self):
        queryset = Post.objects.filter(status='published')
        
        # Filtrar por tag si existe
        tag_slug = self.kwargs.get('tag_slug')
        if tag_slug:
            tag = get_object_or_404(Tag, slug=tag_slug)
            queryset = queryset.filter(tags__in=[tag])
            
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        # Agregar tag al contexto si existe
        tag_slug = self.kwargs.get('tag_slug')
        if tag_slug:
            context['tag'] = get_object_or_404(Tag, slug=tag_slug)
            
        # Agregar tags populares
        context['popular_tags'] = Tag.objects.annotate(
            posts_count=Count('taggit_taggeditem_items')
        ).order_by('-posts_count')[:10]
        context['all_tags'] = Tag.objects.annotate(
            posts_count=Count('taggit_taggeditem_items')
        ).order_by('name')
        
        return context

class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post'
    
    def get_queryset(self):
        return Post.objects.filter(status='published')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        # Obtener post actual
        post = self.get_object()
        
        # Posts relacionados por tags
        post_tags_ids = post.tags.values_list('id', flat=True)
        similar_posts = Post.objects.filter(status='published')\
                                  .filter(tags__in=post_tags_ids)\
                                  .exclude(id=post.id)
        similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
                                   .order_by('-same_tags', '-publish')[:3]
        context['all_tags'] = Tag.objects.annotate(
            posts_count=Count('taggit_taggeditem_items')
        ).order_by('name')
        
        context['similar_posts'] = similar_posts
        return context

web/views.py
from django.shortcuts import render, redirect
from django.utils import translation
from django.conf import settings
import logging

logger = logging.getLogger(__name__)


def index(request):
    return render(request, 'index.html')


def residencia_canina(request):
    return render(request, 'residencia_canina.html')


def educacion_canina(request):
    return render(request, 'educacion_canina.html')


def intervenciones_asistidas_por_perros(request):
    return render(request, 'intervenciones_asistidas_por_perros.html')

def nuestro_club(request):
    return render(request, 'nuestro_club.html')


def equipo(request):
    return render(request, 'equipo.html')


def contacto(request):
    return render(request, 'contacto.html')


def instalaciones(request):
    return render(request, 'instalaciones.html')


def google(request):
    return render(request, 'google.html')


def change_language(request):
    if settings.LANGUAGE_COOKIE_NAME not in request.session:
        request.session[settings.LANGUAGE_COOKIE_NAME] = "es"
    current_language = request.session[settings.LANGUAGE_COOKIE_NAME]
    
    if current_language == "gl":
        lang_code = "es"
    else:
        lang_code = "gl"

    translation.activate(lang_code)
    request.session[settings.LANGUAGE_COOKIE_NAME] = lang_code

    next_url = request.META.get('HTTP_REFERER', '/')
    response = redirect(next_url)
    return response

templates/base.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
   <head>

      <!-- Google tag (gtag.js) -->
      <script async src="https://www.googletagmanager.com/gtag/js?id=G-PVN6B6PT21"></script>
      <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-PVN6B6PT21');
      </script>

      <meta charset="utf-8">
      <!--[if IE]>
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <![endif]-->
      <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
      {% block meta %}
      {% endblock %}
      <!-- page title -->
      <title>Alcanza</title>
      <!--[if lt IE 9]>
      <script src="js/respond.js"></script>
      <![endif]-->
      <!-- Font files -->
      <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700%7CQuicksand:400,500,700&display=swap" rel="stylesheet">
      <link href="{% static 'fonts/flaticon/flaticon.css' %}" rel="stylesheet" type="text/css">
      <link href="{% static 'fonts/fontawesome/fontawesome-all.min.css' %}" rel="stylesheet" type="text/css">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css" integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog==" crossorigin="anonymous" referrerpolicy="no-referrer" />
      <!-- Fav icons -->
      <link rel="apple-touch-icon" sizes="57x57" href="{% static 'apple-icon-57x57.png' %}">
      <link rel="apple-touch-icon" sizes="72x72" href="{% static 'apple-icon-72x72.png' %}">
      <link rel="apple-touch-icon" sizes="114x114" href="{% static 'apple-icon-114x114.png' %}">
      <link rel="shortcut icon" type="image/x-icon" href="{% static 'favicon.ico' %}">
      <!-- Bootstrap core CSS -->
      <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
      <!-- style CSS -->
      <link href="{% static 'css/style.css' %}" rel="stylesheet">
      <!-- plugins CSS -->
      <link href="{% static 'css/plugins.css' %}" rel="stylesheet">
      <!-- Colors CSS -->
      <link href="{% static 'styles/maincolors.css' %}" rel="stylesheet">
      <!-- LayerSlider CSS -->
      <link rel="stylesheet" href="{% static 'vendor/layerslider/css/layerslider.css' %}">
   </head>

   <!-- ==== body starts ==== -->

   <body id="top">
      <!-- Preloader-->
      <div id="preloader">
         <div class="spinner">
            <div class="bounce1"></div>
         </div>
      </div>
      <!-- /Preloader ends -->
      <nav id="main-nav" class="navbar-expand-xl">
         <!-- Start Top Bar -->
         <div class="container-fluid top-bar">
            <div class="container">
               <div class="row">
                  <div class="col-md-8 d-none d-md-block">
                     <!-- Start Contact Info -->
                     <ul class="contact-details float-left">
                        <li><i class="fa fa-map-marker"></i> Lugar Ermelo 14A - Bueu</li>
                        <li class="d-none d-xl-inline"><i class="fa fa-envelope"></i><a href="mailto:contacta@alcanzaespazocanino.es">contacta@alcanzaespazocanino.es</a></li>
                        <li><i class="fa fa-phone"></i>629 03 75 66</li>
                     </ul>
                     <!-- End Contact Info -->
                  </div>
                  <!-- /col -->
                  <div class="col-12 col-md-4 float-start">
                     <ul class="social-list list-inline d-inline d-md-none">
                        <li class="list-inline-item"><a  title="Instagram" href="#"><i class="fab fa-instagram"></i></a></li>
                        <li class="list-inline-item"><a  title="TikTok" href="#"><i class="fab fa-tiktok"></i></a></li>
                     </ul>
                     <!-- Start Social Links -->
                     <ul class="social-list float-end list-inline">
                        <li class="list-inline-item d-none d-md-inline"><a  title="Instagram" href="https://www.instagram.com/alcanza_espazocanino/"><i class="fab fa-instagram"></i></a></li>
                        <li class="list-inline-item d-none d-md-inline"><a  title="TikTok" href="https://tiktok.com/@alcanza_espazocanino"><i class="fab fa-tiktok"></i></a></li>
                        <li class="list-inline-item ms-5"><a  title="Lenguaje" href="{% url 'change_language' %}"><i class="fa fa-globe me-2 me-md-0"></i></a>{% trans "ES" %}</li>
                     </ul>
                     <!-- /End Social Links -->
                  </div>
                  <!-- /col -->
               </div>
               <!-- /row -->
            </div>
            <!-- /container -->
         </div>
         <!-- End Top bar -->
         
         <!-- Navbar Starts -->
         <div class="navbar container-fluid">
            <div class="container">
               <!-- logo -->
               <a class="navbar-brand" href="/">
                  <img src="{% static 'img/alcanza-logo.png' %}" height="80px"> 
                  <span>Alcanza</span>
               </a>
               <!-- Navbartoggler -->
               <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
               <span class="navbar-toggle-icon">
               <i class="fas fa-bars"></i>
               </span>
               </button>
               <div class="collapse navbar-collapse" id="navbarResponsive">
                  <ul class="navbar-nav ms-auto">
                     <!-- menu item -->
                     <li class="nav-item">
                        <a class="nav-link" href="/">{% trans "Inicio" %}
                        </a>
                     </li>
                     <!-- menu item -->
                     <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="services-dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        {% trans "Servicios" %}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="services-dropdown">
                           <a class="dropdown-item" href="/residencia-canina">{% trans "Residencia canina" %}</a>
                           <a class="dropdown-item" href="/educacion-canina">{% trans "Educación canina" %}</a>
                           <a class="dropdown-item" href="/intervenciones-asistidas-por-perros">{% trans "Intervenciones asistidas por perros" %}</a>
                           <a class="dropdown-item" href="/nuestro-club">{% trans "Nuestro club" %}</a>
                        </div>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="/instalaciones">{% trans "Instalaciones" %}
                        </a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="/equipo">{% trans "Equipo" %}
                        </a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="/blog">{% trans "Blog" %}
                        </a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link" href="/contacto">{% trans "Contacto" %}
                        </a>
                     </li>
                     <!-- menu item -->
                  </ul>
                  <!--/ul -->
               </div>
               <!--collapse -->
            </div>
            <!-- /container -->
         </div>
         <!-- /navbar -->
      </nav>
      <!-- /nav -->

      {% block content %}
      {% endblock %}
   
      <!-- ==== footer ==== -->
      <footer class="text-light">
         <div class="container">
            <div class="row">
               <div class="col-lg-8">
                  <a class="navbar-brand" href="/"><i class="flaticon-dog-20"></i><span>Alcanza</span></a>
                  <p class="mt-3">{% trans "Forjando vínculos fuertes, alcanzando metas juntos." %}</p>
               </div>
               <!--/ col-lg -->
               <div class="col-lg-4">
                  <h6><i class="fas fa-envelope margin-icon"></i>{% trans "Contacto" %}</h6>
                  <ul class="list-unstyled">
                     <li>629 03 75 66</li>
                     <li><a href="mailto:contacta@alcanzaespazocanino.es">contacta@alcanzaespazocanino.es</a></li>
                     <li>Lugar Ermelo 14A - Bueu </li>
                  </ul>

                  <ul class="list-inline">
                     <li class="list-inline-item"><a  title="Instagram" href="#"><i class="fab fa-instagram"></i></a></li>
                     <li class="list-inline-item"><a title="TikTok" href="#"><i class="fab fa-tiktok"></i></a></li>
                  </ul>
                  <!--/ul -->
               </div>
               <!--/ col-lg -->
            </div>
         </div>
         <!--/ container -->
         <!-- Go To Top Link -->
         <div class="d-none d-md-block">
            <a href="#top" class="back-to-top"><i class="fa fa-angle-up"></i></a>
         </div>
         <!--/page-scroll-->
      </footer>
      <div class="text-center">
         <img src="{% static 'img/logo_kit_digital.jpg' %}" 
         class ="my-3 px-5 mw-100"
         height="80px"> 
      </div>

      <!--/ footer-->

      <script>
         var static_url = "{% get_static_prefix %}";
     </script>

      <!-- Bootstrap core & Jquery -->
      <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
      <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
      <!-- Custom Js -->
      <script src="{% static 'js/custom.js' %}"></script>
      <script src="{% static 'js/plugins.js' %}"></script>
      <!-- Prefix free -->
      <script src="{% static 'js/prefixfree.min.js' %}"></script>
      <!-- GreenSock -->
      <script src="{% static 'vendor/layerslider/js/greensock.js' %}"></script>
      <!-- LayerSlider script files -->
      <script src="{% static 'vendor/layerslider/js/layerslider.transitions.js' %}"></script>
      <script src="{% static 'vendor/layerslider/js/layerslider.kreaturamedia.jquery.js' %}"></script>
      <script src="{% static 'vendor/layerslider/js/layerslider.load.js' %}"></script>
      <!-- Mailchimp script -->
      <script src="{% static 'js/mailchimp.js' %}"></script>
      <!-- number counter script -->
      <script src="{% static 'js/counter.js' %}"></script>
      <!-- Contact Form script -->
      <script src="{% static 'js/contact.js' %}"></script>
      <!-- Map -->
      <script src="{% static 'js/map.js' %}"></script>      
   </body>
</html>

templates/blog/detail.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block meta %}
    <meta name="description" content="{{ post.meta_description }}">
    <meta name="keywords" content="{{ post.meta_keywords }}">
{% endblock %}

{% block content %}


<!-- Jumbotron -->
<div class="jumbotron jumbotron-fluid overlay jumbotron-instalaciones">
<div class="jumbo-heading">
    <!-- section-heading -->
    <div class="section-heading" data-aos="zoom-in">
        <h1>{{post.title}}</h1>
    </div>
    <!-- /section-heading -->
    <!-- Breadcrumbs -->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="index.html">{% trans "Inicio" %}</a></li>
            <li class="breadcrumb-item"><a href="blog">Blog</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{post.title}}</li>
        </ol>
    </nav>
</div>
<!-- /jumbo-heading -->
</div>
<!-- /jumbotron -->
<!-- ==== Page Content ==== -->
<div class="page">
<div class="container">
    <div class="row">
        <!-- Post Content Column -->
        <div class="col-lg-8 col-xl-9 card blog-card">
            <div class="card-body">
                <!-- Post info-->

                <div class="post-content">
                    {{ post.get_markdown_content }}
                </div>
                <hr>
                <div class="post-info border-irregular2 text-muted">
                    Escrito por {{post.author}} el {{post.publish.date}}
                </div>
                <p class="tags">
                    {% for tag in post.tags.all %}
                    <a href="{% url 'blog:post_list_by_tag' tag.slug %}" 
                        class="badge badge-pill badge-default">{{ tag.name }}
                    </a>
                    {% endfor %}
                </p>
            </div>
        </div>
        <!-- /col-lg -->

        <!-- Sidebar Widgets Column -->
        {% include "blog/sidebar.html" %}
    </div>
    <!-- /.row -->
</div>
<!-- /.container -->
</div>
<!-- /page -->



{% endblock %}

templates/blog/list.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block content %}


<!-- Jumbotron -->
<div class="jumbotron jumbotron-fluid overlay jumbotron-instalaciones">
<div class="jumbo-heading">
    <!-- section-heading -->
    <div class="section-heading" data-aos="zoom-in">
        <h1>Blog</h1>
    </div>
    <!-- /section-heading -->
    <!-- Breadcrumbs -->
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="index.html">{% trans "Inicio" %}</a></li>
            <li class="breadcrumb-item active" aria-current="page">Blog</li>
        </ol>
    </nav>
</div>
<!-- /jumbo-heading -->
</div>
<!-- /jumbotron -->
<!-- ==== Page Content ==== -->
<div id="blog-home" class="page">
<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-lg-8 col-xl-9">
            <!-- Blog Post -->

            {% for post in posts %}
            <article class="card blog-card">
                <!-- Post info-->
                <a href="{{ post.get_absolute_url }}">
                    {% if post.featured_image %}
                    <img class="card-img-top img-fluid" src="{{ post.featured_image.url }}" >
                    {% endif %}
                </a>
                <div class="card-body">
                    <a href="{{ post.get_absolute_url }}">
                        <h2 class="card-title"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
                    </a>
                    <div class="post-info border-irregular2 text-muted">
                        Escrito por {{post.author.first_name}} {{post.author.last_name}} el {{post.publish.date}}
                    </div>
                    <p>{{ post.summary }}</p>
                    
                    <a href="{{ post.get_absolute_url }}" class="btn btn-primary">Leer más &rarr;</a>
                </div>
                <!--card-footer -->

            </article>
            {% endfor %}

        </div>
        <!-- /col-lg-8 -->

        <!-- Sidebar Widgets Column -->
        {% include "blog/sidebar.html" %}

    </div>
    <!-- /.row -->
</div>
<!-- /.container -->
</div>



{% endblock %}

templates/blog/sidebar.html
{% load static %}
{% load i18n %}

<div class="blog-sidebar bg-light-custom  h-50 border-irregular1 col-lg-4 col-xl-3 text-center">
    <div class="card">
        <h5 class="card-header">Blog Alcanza</h5>
        <div class="card-body">
            <img src="{% static 'img/alcanza-logo.png' %}" class="img-fluid">
            <p class="mt-2">Falemos de cans, consellos e noticias.</p>
        </div>
     </div>

    <div class="card">
        <h5 class="card-header">Etiquetas</h5>
        <div class="card-body">
            {% for tag in all_tags%}
            <a href="{% url 'blog:post_list_by_tag' tag.slug %}" 
                class="badge badge-pill badge-default">{{ tag.name }}
            </a>
            {% endfor %}
        </div>
    </div>
</div>

templates/contacto.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block content %}

<div class="jumbotron jumbotron-fluid overlay jumbotron-contacto">
   <div class="jumbo-heading">
      <!-- section-heading -->
      <div class="section-heading" data-aos="zoom-in">
         <h1>{% trans "Contacto y horario" %}</h1>
      </div>
      <!-- /section-heading -->
      <!-- Breadcrumbs -->
      <nav aria-label="breadcrumb">
         <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="index.html">{% trans "Inicio" %}</a></li>
            <li class="breadcrumb-item active" aria-current="page">{% trans "Contacto" %}</li>
         </ol>
      </nav>
   </div>
   <!-- /jumbo-heading -->
</div>
<!-- /jumbotron -->

<!-- ==== Page Content ==== -->
<div class="page pb-0">
   <div class="container block-padding pt-0">
      <div class="row">
         <div class="col-md-6 mb-5">
            <img src="{% static 'img/horario-general.png' %}" alt="" class="img-fluid border-irregular2"  data-aos="zoom-in"  >
         </div>
         <div class="col-md-6 mb-5">
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d492.34506908364483!2d-8.763296831174124!3d42.30550089936032!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd2f66ba3f894b0f%3A0xd2e002f283471341!2sLugar%20Ermelo%2C%2014D%2C%2036938%2C%20Pontevedra!5e0!3m2!1ses!2ses!4v1715096105711!5m2!1ses!2ses" width="100%" height="400" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
         </div>
      </div>
   </div>
   <div class="container">
      <div class="row text-xs-center text-sm-center text-md-center text-lg-start">
         <!-- contact-info-->
         <div class="contact-info col-lg-5 mb-5">
            <h4>{% trans "¡Contáctanos!" %}</h4>
            <!-- Form Starts -->
            <div id="contact_form">
               <div class="form-group">
                  <div class="row">
                     <div class="col-md-6">
                        <label>{% trans "Nombre" %}<span class="required">*</span></label>
                        <input type="text" name="name" class="form-control input-field" required="">
                     </div>
                     <div class="col-md-6">
                        <label>{% trans "Email" %} <span class="required">*</span></label>
                        <input type="email" name="email" class="form-control input-field" required="">
                     </div>
                  </div>
                  <div class="row">
                     <div class="col-md-12">
                        <label>{% trans "Asunto" %}</label>
                        <input type="text" name="subject" class="form-control input-field">
                     </div>
                     <div class="col-md-12">
                        <label>{% trans "Mensaje" %}<span class="required">*</span></label>
                        <textarea name="message" id="message" class="textarea-field form-control" rows="3"
                           required=""></textarea>
                     </div>
                  </div>
                  <button type="submit" id="submit_btn" value="Submit" class="btn btn-primary">{% trans "Enviar mensaje"%}</button>
               </div>
               <!-- /form-group-->
               <!-- Contact results -->
               <div id="contact_results"></div>
            </div>
            <!-- /contact)form-->
         </div>
         <!-- /contact-info-->
         <div class="col-lg-6 offset-lg-1 h-50 card bg-secondary res-margin mb-5">
            <div class="contact-info text-light ">
               <!-- contact-info-->
               <div class="text-light">
                  <h5>{% trans "Información" %} </h5>
                  <p>{% trans "Os dejamos por aquí nuestros datos de contacto, si tienes cualquier pregunta no dudes en ponerte en contacto con nosotras. Si quieres estar al tanto de todas nuestras novedades síguenos en nuestras redes sociales." %}
                  </p>
                  <!-- contact icons-->
                  <ul class="list-unstyled mt-5 list-contact">
                     <li class="h7"><i class="fa fa-envelope margin-icon"></i><a
                           href="mailto:contacta@alcanzaespazocanino.es">contacta@alcanzaespazocanino.es</a></li>
                     <li class="h7"><i class="fa fa-phone margin-icon"></i>629 03 75 66</li>
                     <li class="h7"><i class="fa fa-map-marker margin-icon"></i>Lugar Ermelo 14A (Carretera de Ermelo a
                        Moaña) Bueu.</li>
                     <li class="h7 mt-4">
                        <a href="https://www.instagram.com/alcanza_espazocanino/"><i class="fab fa-instagram fa-2x me-2"></i></a>
                        <a href="https://tiktok.com/@alcanza_espazocanino"><i class="fab fa-tiktok fa-2x"></i></a>
                     </li>
                  </ul>
                  <!-- /list-->
               </div>
               <!-- /text-light -->
            </div>
            <!-- /contact-info-->
         </div>
         <!-- /col-lg-->
      </div>
      <!-- /row-->
   </div>
   <!-- /container -->
</div>

{% endblock %}

templates/idioma.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}

{% block content %}

Tu idioma es {{idioma}}
Tu session es {{idioma_session}}

{% endblock %}